# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jupyter Notebooks
author: Rick de Klerk
logo: figures/logo_dcc.png
copyright: "2022, CC BY 4.0"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/rickdkk/DCC-workshop  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: figures/logo_dcc.png  # A path to a favicon image
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  extra_navbar: Onderdeel van het <a href="https://wiki.surfnet.nl/display/DPO/DCC+Praktijkgericht+onderzoek">DCC-PO</a>  # Will be displayed underneath the left navbar.

sphinx:
  config:
    language: nl
